#!/bin/bash

# This is a thin wrapper around bitcoinrtx-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using bitcoinrtx-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_BITCOINRTXD

# Grab the value of $REAL_BITCOINRTXCLI which may be bitcoinrtx-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_BITCOINRTXCLI}" "$@" | sed 's/\r//'
